version: "3.8"

services:
  lamora:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lamora
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - shared-web-network

networks:
  shared-web-network:
    external: true
